"""Windows backend (runs natively or from WSL via powershell.exe interop).

detect/listen: PowerShell + Raw Input API (per-device keystroke attribution).
apply: generates an AutoHotkey v2 script.
  - mode 'interception' (default): uses AutoHotInterception -> true per-device
    blocking. Requires the Interception driver (admin install + one reboot).
  - mode 'heuristic': plain AHK, no driver. Distinguishes the keypad by its
    NumLock-churn fingerprint. Degraded: only works for devices with that
    quirk; use only if the driver is not an option.
"""

import os
import re
import shutil
import subprocess

from ..config import Config
from ..keys import KEYS, AHK_MOD_PREFIX

ASSETS = os.path.join(os.path.dirname(__file__), "..", "..", "assets")


def _ps(args: list[str], **kw) -> subprocess.CompletedProcess:
    return subprocess.run(["powershell.exe", "-NoProfile", *args],
                          capture_output=True, text=True, **kw)


def ps(args: list[str], timeout: int = 20) -> tuple[int, str]:
    """PowerShell helper used by doctor: returns (returncode, combined output)."""
    try:
        r = _ps(args, timeout=timeout)
        return r.returncode, (r.stdout or "") + (r.stderr or "")
    except Exception as e:  # noqa: BLE001
        return 1, f"{type(e).__name__}: {e}"


AHK_CANDIDATES = (
    r"%LOCALAPPDATA%\Programs\AutoHotkey\v2\AutoHotkey64.exe",
    r"%ProgramFiles%\AutoHotkey\v2\AutoHotkey64.exe",
)


def find_autohotkey() -> str | None:
    """Windows path of AutoHotkey v2, or None. Works from WSL too."""
    rc, out = ps(["-Command",
                  "$p=@(\"$env:LOCALAPPDATA\\Programs\\AutoHotkey\\v2\\AutoHotkey64.exe\","
                  "\"$env:ProgramFiles\\AutoHotkey\\v2\\AutoHotkey64.exe\");"
                  "foreach($x in $p){ if(Test-Path $x){ $x; break } }"])
    path = out.strip().splitlines()[0].strip() if rc == 0 and out.strip() else ""
    return path or None


def lib_dir_hint() -> str | None:
    """Where AutoHotInterception's Lib/ was found, if anywhere."""
    for base in (os.path.join(ASSETS, "..", "out"),):
        for root, dirs, _ in os.walk(os.path.abspath(base)):
            if "Lib" in dirs:
                return os.path.join(root, "Lib")
    rc, out = ps(["-Command",
                  "$d=\"$env:USERPROFILE\\keyremap\\Lib\"; if(Test-Path $d){$d}"])
    p = out.strip() if rc == 0 else ""
    return p or None


def _stage_script(name: str) -> str:
    """Copy an asset .ps1 to Windows temp; return its Windows path."""
    from ..envinfo import windows_temp_dir, to_windows_path
    src = os.path.join(ASSETS, name)
    dst_dir = os.path.join(windows_temp_dir(), "keyremap")
    os.makedirs(dst_dir, exist_ok=True)
    dst = os.path.join(dst_dir, name)
    shutil.copyfile(src, dst)
    return to_windows_path(dst)


def detect(cfg: Config) -> list[dict]:
    r = _ps(["-Command",
             "Get-PnpDevice | Where-Object { ($_.Class -eq 'Keyboard' -or "
             "$_.FriendlyName -match 'keypad|keyboard') -and $_.Status -eq 'OK' } | "
             "ForEach-Object { $_.FriendlyName + '|' + $_.InstanceId }"])
    devices = []
    for line in r.stdout.splitlines():
        if "|" not in line:
            continue
        name, inst = line.split("|", 1)
        m = re.search(r"VID&?_?0?2?(?P<vid>[0-9A-F]{4})_PID&?_?(?P<pid>[0-9A-F]{4})",
                      inst, re.I)
        vid = int(m.group("vid"), 16) if m else None
        pid = int(m.group("pid"), 16) if m else None
        matched = [ln for ln, dm in cfg.devices.items()
                   if dm.matches(vid, pid, name)]
        devices.append({"name": name.strip(), "instance": inst.strip(),
                        "vid": vid, "pid": pid, "matches": matched})
    return devices


def listen(cfg: Config, seconds: int = 30):
    script = _stage_script("RawKbListen.ps1")
    proc = subprocess.Popen(
        ["powershell.exe", "-NoProfile", "-ExecutionPolicy", "Bypass",
         "-File", script, "-Seconds", str(seconds)],
        stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True)
    assert proc.stdout is not None
    for line in proc.stdout:
        yield line.rstrip("\n")
    proc.wait()


def _ahk_send(mods: list[str], key: str) -> str:
    prefix = "".join(AHK_MOD_PREFIX[m] for m in mods)
    return f'{prefix}{{{KEYS[key].ahk}}}'


def generate_interception(cfg: Config) -> str:
    """AutoHotkey v2 + AutoHotInterception script (true per-device blocking)."""
    out = [
        '#Requires AutoHotkey v2.0',
        '#SingleInstance Force',
        'Persistent',
        '#Include Lib\\AutoHotInterception.ahk',
        '',
        '; Generated by keyremap - do not edit by hand; edit config.yaml and re-run apply.',
        'Status(line) {',
        '    try FileAppend(line "`r`n", A_ScriptDir "\\ahk-status.log")',
        '}',
        'try {',
        '    AHI := AutoHotInterception()',
        '} catch as e {',
        '    Status("AHI init failed: " e.Message)',
        '    ExitApp',
        '}',
        'Status("=== interception start " A_Now)',
        '',
        '; Modifiers held via remapped keys. Released on exit and by the',
        '; watchdog below so a missed key-up can never leave one stuck.',
        'global heldMods := Map()',
        '; Physically-down state per source key, so keyboard auto-repeat is not',
        '; mistaken for repeated presses (it would spam the press action and',
        '; keep restarting the hold timer, so the hold action never fires).',
        'global keyDown := Map()',
        '; Keys whose hold action already fired, so the tap action is skipped',
        '; when the key is finally released.',
        'global holdFired := Map()',
        'ReleaseHeld(*) {',
        '    global heldMods',
        '    for m, t in heldMods.Clone()',
        '        Send "{" m " Up}"',
        '    heldMods.Clear()',
        '}',
        'OnExit(ReleaseHeld)',
        '; Failsafe: a dropped Bluetooth key-up would leave a modifier stuck',
        '; down forever. GetKeyState cannot be used here (the source key is',
        '; blocked at driver level, so Windows never sees it), so release any',
        '; modifier held longer than MOD_MAX_HOLD ms.',
        'MOD_MAX_HOLD := 30000',
        'SetTimer(ModWatchdog, 1000)',
        'ModWatchdog() {',
        '    global heldMods, MOD_MAX_HOLD',
        '    for m, t in heldMods.Clone() {',
        '        if (A_TickCount - t > MOD_MAX_HOLD) {',
        '            Send "{" m " Up}"',
        '            heldMods.Delete(m)',
        '            Status("watchdog released stuck " m)',
        '        }',
        '    }',
        '}',
        '',
    ]
    for dev, table in cfg.mappings.items():
        dm = cfg.devices[dev]
        if dm.vendor_id is None or dm.product_id is None:
            raise ValueError(f"device {dev!r} needs vendor_id+product_id for the "
                             "Windows interception backend")
        var = f"id_{dev}"
        # Match by device HANDLE, not GetKeyboardId(vid,pid): Bluetooth-LE HID
        # devices report VID/PID as 0x0000 to the Interception driver, and the
        # vid/pid lookup pops its own MsgBox and aborts when it misses.
        # Handles look like: HID\{...}_Dev_VID&02045e_PID&0040_REV&0300&Col01
        ble_frag = f"VID&02{dm.vendor_id:04x}_PID&{dm.product_id:04x}"
        out.append(f'{var} := 0')
        out.append('for d in AHI.GetInstance().GetDeviceList() {')
        out.append(f'    if (!d.IsMouse && InStr(d.Handle, "{ble_frag}"))')
        out.append(f'        {var} := d.Id')
        out.append('}')
        out.append(f'if ({var} = 0) {{')
        out.append(f'    Status("device {dev} not visible to driver - exiting")')
        out.append('    ExitApp')
        out.append('}')
        for src, act in table.items():
            k = KEYS[src]
            sc = k.sc | (0x100 if k.ext else 0)  # AHI marks E0-extended with 0x100
            fn = f"On_{dev}_{src}"
            out.append(f'AHI.SubscribeKey({var}, 0x{sc:X}, true, {fn})')
            if not act.is_simple:
                # press -> on key-down; tap -> on release if quick;
                # hold -> at the hold_ms mark while still held (suppresses tap).
                hold_fn = f"Hold_{dev}_{src}"
                # NOTE: only ever ASSIGN to these maps - AHK v2's Map.Delete()
                # throws when the key is absent, which would kill the callback.
                out.append(f'{fn}(state) {{')
                out.append('    global keyDown, holdFired')
                out.append('    try {')
                out.append('    if (state) {')
                out.append(f'        if (keyDown.Get("{src}", false))')
                out.append('            return  ; auto-repeat: ignore, do not restart timer')
                out.append(f'        keyDown["{src}"] := true')
                out.append(f'        holdFired["{src}"] := false')
                for pmods, pdst in (act.press or []):
                    out.append(f'        Send "{_ahk_send(pmods, pdst)}"')
                    out.append(f'        Status("FIRED {src} press -> {pdst}")')
                if act.hold is not None:
                    out.append(f'        SetTimer({hold_fn}, -{act.hold_ms})')
                out.append('    } else {')
                out.append(f'        keyDown["{src}"] := false')
                if act.hold is not None:
                    out.append(f'        SetTimer({hold_fn}, 0)  ; cancel pending hold')
                if act.tap is not None:
                    out.append(f'        if (!holdFired.Get("{src}", false)) {{')
                    for tmods, tdst in act.tap:
                        out.append(f'            Send "{_ahk_send(tmods, tdst)}"')
                        out.append(f'            Status("FIRED {src} TAP -> {tdst}")')
                    out.append('        }')
                out.append(f'        holdFired["{src}"] := false')
                out.append('    }')
                out.append(f'    }} catch as e {{')
                out.append(f'        Status("ERROR in {fn}: " e.Message)')
                out.append('    }')
                out.append('}')
                if act.hold is not None:
                    out.append(f'{hold_fn}() {{')
                    out.append('    global holdFired')
                    out.append(f'    holdFired["{src}"] := true  ; suppress tap on release')
                    for hmods, hdst in act.hold:
                        out.append(f'    Send "{_ahk_send(hmods, hdst)}"')
                        out.append(f'    Status("FIRED {src} HOLD -> {hdst}")')
                    out.append('}')
                continue
            mods, dst = act.press[0]
            if dst in AHK_MOD_PREFIX and not mods:
                # Modifier target: must be HELD for the duration of the press,
                # not tapped, so other keys combine with it.
                ahk = KEYS[dst].ahk
                out.append(f'{fn}(state) {{')
                out.append('    global heldMods')
                out.append('    if (state) {')
                out.append(f'        Send "{{{ahk} Down}}"')
                out.append(f'        heldMods["{ahk}"] := A_TickCount')
                out.append('    } else {')
                out.append(f'        Send "{{{ahk} Up}}"')
                out.append(f'        if (heldMods.Has("{ahk}"))')
                out.append(f'            heldMods.Delete("{ahk}")')
                out.append('    }')
                out.append(f'    Status("FIRED {src} -> {dst} " (state ? "down" : "up"))')
                out.append('}')
            else:
                out.append(f'{fn}(state) {{')
                out.append('    if (state) {')
                out.append(f'        Send "{_ahk_send(mods, dst)}"')
                out.append(f'        Status("FIRED {src} -> {dst}")')
                out.append('    }')
                out.append('}')
        out.append(f'Status("subscribed OK on device id " {var} " - remap ACTIVE")')
        out.append('')
    return "\n".join(out) + "\n"


def generate_heuristic(cfg: Config) -> str:
    """Driver-free fallback: distinguishes the keypad by NumLock-churn timing.

    Only reliable for devices with the NumLock quirk; window is 80 ms.
    """
    out = [
        '#Requires AutoHotkey v2.0',
        '#SingleInstance Force',
        'Persistent',
        '',
        '; Generated by keyremap (HEURISTIC mode - no driver).',
        '; A mapped key is treated as keypad input if NumLock was seen < 300 ms before it.',
        '; NumLock churn must PASS THROUGH (~): the keypad firmware watches the',
        '; NumLock LED feedback and stops signalling if its toggles are swallowed,',
        '; which would destroy the fingerprint this mode depends on.',
        'global lastNumLock := 0',
        '',
        '~*NumLock:: {',
        '    global lastNumLock',
        '    lastNumLock := A_TickCount',
        '}',
        '',
    ]
    for dev, table in cfg.mappings.items():
        for src, act in table.items():
            if not act.is_simple:
                out.append(f'; NOTE: {src} has tap/hold actions, unsupported in '
                           'heuristic mode - emitting its first action only.')
            mods, dst = (act.press or act.tap or act.hold)[0]
            k = KEYS[src]
            # vk-based hotkey names are robust for punctuation keys like '='
            out.append(f'$*vk{k.vk:X}:: {{  ; {src}')
            out.append('    global lastNumLock')
            out.append('    if (A_TickCount - lastNumLock < 300)')
            out.append(f'        Send "{_ahk_send(mods, dst)}"')
            out.append('    else')
            out.append(f'        Send "{{Blind}}{{vk{k.vk:X}}}"')
            out.append('}')
            out.append('')
    return "\n".join(out) + "\n"


def apply(cfg: Config, out_dir: str, mode: str = "interception",
          dry_run: bool = False) -> str:
    gen = generate_interception if mode == "interception" else generate_heuristic
    text = gen(cfg)
    path = os.path.join(out_dir, f"keyremap_{mode}.ahk")
    if not dry_run:
        os.makedirs(out_dir, exist_ok=True)
        with open(path, "w", newline="\r\n") as f:
            f.write(text)
    return path if not dry_run else text
